# Generated by Django 5.2.6 on 2025-12-11 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Videojuegos', '0002_cliente_imagen_empleado_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad_minima', models.IntegerField()),
                ('clasificacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=255)),
                ('CP', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='videojuegos/')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('ano_lanzamiento', models.IntegerField()),
                ('compania', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Videojuegos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juego', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Videojuegos.proveedor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Videojuegos.sucursal')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Videojuegos.videojuego')),
            ],
        ),
    ]
