from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio_videojuegos, name='inicio'),
    path('agregar_cliente/', views.agregar_cliente, name='agregar_cliente'),
    path('ver_clientes/', views.ver_clientes, name='ver_clientes'),
    path('actualizar_cliente/<int:id>/', views.actualizar_cliente, name='actualizar_cliente'),
    path('borrar_cliente/<int:id>/', views.borrar_cliente, name='borrar_cliente'),
    path('agregar_empleado/', views.agregar_empleado, name='agregar_empleado'),
    path('ver_empleados/', views.ver_empleados, name='ver_empleados'),
    path('actualizar_empleado/<int:id>/', views.actualizar_empleado, name='actualizar_empleado'),
    path('borrar_empleado/<int:id>/', views.borrar_empleado, name='borrar_empleado'),
    path('agregar_venta/', views.agregar_venta, name='agregar_venta'),
    path('ver_ventas/', views.ver_ventas, name='ver_ventas'),
    path('actualizar_venta/<int:id>/', views.actualizar_venta, name='actualizar_venta'),
    path('borrar_venta/<int:id>/', views.borrar_venta, name='borrar_venta'),
    path('agregar_sucursal/', views.agregar_sucursal, name='agregar_sucursal'),
    path('ver_sucursales/', views.ver_sucursales, name='ver_sucursales'),
    path('actualizar_sucursal/<int:pk>/', views.actualizar_sucursal, name='actualizar_sucursal'),
    path('borrar_sucursal/<int:pk>/', views.borrar_sucursal, name='borrar_sucursal'),
    path('agregar_proveedor/', views.agregar_proveedor, name='agregar_proveedor'),
    path('ver_proveedores/', views.ver_proveedores, name='ver_proveedores'),
    path('actualizar_proveedor/<int:pk>/', views.actualizar_proveedor, name='actualizar_proveedor'),
    path('borrar_proveedor/<int:pk>/', views.borrar_proveedor, name='borrar_proveedor'),
    path('agregar_categoria/', views.agregar_categoria, name='agregar_categoria'),
    path('ver_categorias/', views.ver_categorias, name='ver_categorias'),
    path('actualizar_categoria/<int:pk>/', views.actualizar_categoria, name='actualizar_categoria'),
    path('borrar_categoria/<int:pk>/', views.borrar_categoria, name='borrar_categoria'),
    path('agregar_videojuego/', views.agregar_videojuego, name='agregar_videojuego'),
    path('ver_videojuegos/', views.ver_videojuegos, name='ver_videojuegos'),
    path('actualizar_videojuego/<int:pk>/', views.actualizar_videojuego, name='actualizar_videojuego'),
    path('borrar_videojuego/<int:pk>/', views.borrar_videojuego, name='borrar_videojuego'),
    path('agregar_inventario/', views.agregar_inventario, name='agregar_inventario'),
    path('ver_inventarios/', views.ver_inventarios, name='ver_inventarios'),
    path('actualizar_inventario/<int:id>/', views.actualizar_inventario, name='actualizar_inventario'),
    path('borrar_inventario/<int:id>/', views.borrar_inventario, name='borrar_inventario'),
]
